env:
  global:
    - PATH=$PATH:$HOME/.cargo/bin
    - RUST_BACKTRACE=1
    - TARGET=x86_64-unknown-linux-musl
os:
  - linux
  - osx
language: rust
rust:
  - stable
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - rustup target add $TARGET
  - rustup component add rustfmt clippy
script:
  - set -x;
    cargo fmt -- --check &&
    cargo clippy --target $TARGET &&
    cargo clippy --target $TARGET --profile test &&
    cargo test --target $TARGET --release --verbose
before_cache:
 - cargo prune
